# Generated by Django 4.2.19 on 2025-02-19 04:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('EMP', 'Employee'), ('CLI', 'Client')], max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news_api.abstractuser')),
                ('plan', models.CharField(max_length=200)),
                ('accessible_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MAIN', 'Main'), ('POW', 'Power'), ('TAX', 'Taxes'), ('HLTH', 'Health'), ('EN', 'Energy'), ('LAB', 'Labor')], max_length=4), blank=True, size=None)),
            ],
            bases=('news_api.abstractuser',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news_api.abstractuser')),
                ('employee_id', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            bases=('news_api.abstractuser',),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='news_images/')),
                ('draft_content', models.TextField()),
                ('published_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_publication_at', models.DateTimeField()),
                ('last_publication_update_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAF', 'Draft'), ('PUBD', 'Published')], max_length=4)),
                ('column', models.CharField(choices=[('MAIN', 'Main'), ('POW', 'Power'), ('TAX', 'Taxes'), ('HLTH', 'Health'), ('EN', 'Energy'), ('LAB', 'Labor')], max_length=4)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news_api.employee')),
            ],
        ),
    ]
