# Generated by Django 4.2.19 on 2025-02-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='abstractuser_ptr',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='abstractuser_ptr',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users_api.employee'),
        ),
        migrations.DeleteModel(
            name='AbstractUser',
        ),
        migrations.DeleteModel(
            name='ClientUser',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
