# Generated by Django 4.2.19 on 2025-02-23 04:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('EMP', 'Employee'), ('CLI', 'Client')], max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(max_length=200)),
                ('accessible_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MAIN', 'Main'), ('POW', 'Power'), ('TAX', 'Taxes'), ('HLTH', 'Health'), ('EN', 'Energy'), ('LAB', 'Labor')], max_length=4), blank=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('EMP', 'Employee'), ('CLI', 'Client')], max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
