services:
  test_web:
    image: nginx:latest
    ports:
      - "5050:80"
  postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # TODO: Create a container for the django app
  # TODO: In the django container, run the create_database_script.py file
volumes:
  postgres_data:



